from __future__ import annotations

from typing import Literal

PluginStatus = Literal[
    "installed",
    "ready",
    "disabled",
    "error",
    "upgrade_pending",
    "uninstalled",
]

PluginCapability = Literal[
    "activity.log.write",
    "agent.sessions.close",
    "agent.sessions.create",
    "agent.sessions.list",
    "agent.sessions.send",
    "agent.tools.register",
    "agents.invoke",
    "agents.pause",
    "agents.read",
    "agents.resume",
    "events.emit",
    "events.subscribe",
    "goals.create",
    "goals.read",
    "goals.update",
    "http.outbound",
    "instance.settings.register",
    "issue.comments.create",
    "issue.comments.read",
    "issues.create",
    "issues.read",
    "issues.update",
    "jobs.schedule",
    "metrics.write",
    "organizations.read",
    "plugin.state.read",
    "plugin.state.write",
    "project.workspaces.read",
    "projects.read",
    "secrets.read-ref",
    "ui.action.register",
    "ui.commentAnnotation.register",
    "ui.dashboardWidget.register",
    "ui.detailTab.register",
    "ui.page.register",
    "ui.sidebar.register",
    "webhooks.receive",
]

PluginUiSlotType = Literal[
    "commentAnnotation",
    "commentContextMenuItem",
    "contextMenuItem",
    "dashboardWidget",
    "detailTab",
    "page",
    "projectSidebarItem",
    "settingsPage",
    "sidebar",
    "sidebarPanel",
    "taskDetailView",
    "toolbarButton",
]

PLUGIN_STATUSES: tuple[PluginStatus, ...] = (
    "installed",
    "ready",
    "disabled",
    "error",
    "upgrade_pending",
    "uninstalled",
)

PLUGIN_CAPABILITIES: tuple[PluginCapability, ...] = (
    "activity.log.write",
    "agent.sessions.close",
    "agent.sessions.create",
    "agent.sessions.list",
    "agent.sessions.send",
    "agent.tools.register",
    "agents.invoke",
    "agents.pause",
    "agents.read",
    "agents.resume",
    "events.emit",
    "events.subscribe",
    "goals.create",
    "goals.read",
    "goals.update",
    "http.outbound",
    "instance.settings.register",
    "issue.comments.create",
    "issue.comments.read",
    "issues.create",
    "issues.read",
    "issues.update",
    "jobs.schedule",
    "metrics.write",
    "organizations.read",
    "plugin.state.read",
    "plugin.state.write",
    "project.workspaces.read",
    "projects.read",
    "secrets.read-ref",
    "ui.action.register",
    "ui.commentAnnotation.register",
    "ui.dashboardWidget.register",
    "ui.detailTab.register",
    "ui.page.register",
    "ui.sidebar.register",
    "webhooks.receive",
)

PLUGIN_UI_SLOT_TYPES: tuple[PluginUiSlotType, ...] = (
    "commentAnnotation",
    "commentContextMenuItem",
    "contextMenuItem",
    "dashboardWidget",
    "detailTab",
    "page",
    "projectSidebarItem",
    "settingsPage",
    "sidebar",
    "sidebarPanel",
    "taskDetailView",
    "toolbarButton",
)
