from __future__ import annotations

ORG_AGENT_LIST_PATH = "/api/orgs/{orgId}/agents"
ORG_AGENT_NAME_SUGGESTION_PATH = "/api/orgs/{orgId}/agents/name-suggestion"
ORG_AGENT_CONFIGURATIONS_PATH = "/api/orgs/{orgId}/agent-configurations"
ORG_ADAPTER_MODELS_PATH = "/api/orgs/{orgId}/adapters/{type}/models"
ORG_ADAPTER_TEST_ENVIRONMENT_PATH = "/api/orgs/{orgId}/adapters/{type}/test-environment"
AGENT_DETAIL_PATH = "/api/agents/{id}"
AGENT_PAUSE_PATH = "/api/agents/{id}/pause"
AGENT_RESUME_PATH = "/api/agents/{id}/resume"
AGENT_TERMINATE_PATH = "/api/agents/{id}/terminate"
AGENT_CONFIGURATION_PATH = "/api/agents/{id}/configuration"
AGENT_CONFIG_REVISIONS_PATH = "/api/agents/{id}/config-revisions"
AGENT_CONFIG_REVISION_PATH = "/api/agents/{id}/config-revisions/{revisionId}"
AGENT_CONFIG_ROLLBACK_PATH = "/api/agents/{id}/config-revisions/{revisionId}/rollback"
AGENT_RUNTIME_STATE_PATH = "/api/agents/{id}/runtime-state"
AGENT_TASK_SESSIONS_PATH = "/api/agents/{id}/task-sessions"
AGENT_RESET_SESSION_PATH = "/api/agents/{id}/runtime-state/reset-session"
AGENT_SKILLS_PATH = "/api/agents/{id}/skills"
AGENT_SKILLS_SYNC_PATH = "/api/agents/{id}/skills/sync"
