ORG_CHAT_LIST_PATH = "/api/orgs/{orgId}/chats"
CHAT_DETAIL_PATH = "/api/chats/{id}"
CHAT_MESSAGES_PATH = "/api/chats/{id}/messages"
CHAT_USER_STATE_PATH = "/api/chats/{id}/user-state"
CHAT_CONTEXT_LINKS_PATH = "/api/chats/{id}/context-links"
CHAT_PROJECT_CONTEXT_PATH = "/api/chats/{id}/project-context"
