from __future__ import annotations

ISSUE_LIST_MISSING_ORG_PATH = "/api/issues"
ORG_ISSUE_LIST_MISSING_ORG_PATH = "/api/orgs/issues"
ORG_ISSUE_LIST_PATH = "/api/orgs/{orgId}/issues"
ISSUE_DETAIL_PATH = "/api/issues/{id}"
ISSUE_CHECKOUT_PATH = "/api/issues/{id}/checkout"
ISSUE_EXECUTE_PATH = "/api/issues/{id}/execute"
ISSUE_PASSIVE_FOLLOWUP_PATH = "/api/issues/{id}/passive-followup"
ISSUE_HEARTBEAT_CONTEXT_PATH = "/api/issues/{id}/heartbeat-context"
ISSUE_COMMENT_LIST_PATH = "/api/issues/{id}/comments"
ISSUE_REVIEW_DECISION_PATH = "/api/issues/{id}/review-decision"
ISSUE_WORK_PRODUCTS_PATH = "/api/issues/{id}/work-products"
WORK_PRODUCT_DETAIL_PATH = "/api/work-products/{id}"
ISSUE_DOCUMENTS_PATH = "/api/issues/{id}/documents"
ISSUE_DOCUMENT_DETAIL_PATH = "/api/issues/{id}/documents/{key}"
ISSUE_DOCUMENT_REVISIONS_PATH = "/api/issues/{id}/documents/{key}/revisions"
