from __future__ import annotations

PLUGIN_LIST_PATH = "/api/plugins"
PLUGIN_AVAILABLE_PATH = "/api/plugins/available"
PLUGIN_EXAMPLES_PATH = "/api/plugins/examples"
PLUGIN_DETAIL_PATH = "/api/plugins/{pluginId}"
PLUGIN_CONFIG_PATH = "/api/plugins/{pluginId}/config"
PLUGIN_CONFIG_TEST_PATH = "/api/plugins/{pluginId}/config/test"
PLUGIN_ENABLE_PATH = "/api/plugins/{pluginId}/enable"
PLUGIN_DISABLE_PATH = "/api/plugins/{pluginId}/disable"
PLUGIN_UNINSTALL_PATH = "/api/plugins/{pluginId}/uninstall"
PLUGIN_UPGRADE_PATH = "/api/plugins/{pluginId}/upgrade"
PLUGIN_HEALTH_PATH = "/api/plugins/{pluginId}/health"
PLUGIN_LOGS_PATH = "/api/plugins/{pluginId}/logs"
PLUGIN_DASHBOARD_PATH = "/api/plugins/{pluginId}/dashboard"
PLUGIN_DATA_PATH = "/api/plugins/{pluginId}/data/{key}"
PLUGIN_ACTION_PATH = "/api/plugins/{pluginId}/actions/{key}"
PLUGIN_JOBS_PATH = "/api/plugins/{pluginId}/jobs"
PLUGIN_JOB_RUNS_PATH = "/api/plugins/{pluginId}/jobs/{jobId}/runs"
PLUGIN_JOB_TRIGGER_PATH = "/api/plugins/{pluginId}/jobs/{jobId}/trigger"
PLUGIN_WEBHOOK_PATH = "/api/plugins/{pluginId}/webhooks/{endpointKey}"
