from __future__ import annotations

import secrets
import re
from collections.abc import Sequence


AGENT_NAME_POOL: tuple[str, ...] = (
    "Ada",
    "Aiden",
    "Aisha",
    "Alex",
    "Amara",
    "Andre",
    "Anika",
    "Ari",
    "Aria",
    "Asher",
    "Avery",
    "Bailey",
    "Bianca",
    "Blake",
    "Cameron",
    "Carmen",
    "Casey",
    "Chloe",
    "Clara",
    "Cora",
    "Cyrus",
    "Dakota",
    "Damon",
    "Daria",
    "Devin",
    "Dylan",
    "Eden",
    "Elias",
    "Eliza",
    "Elliot",
    "Ella",
    "Ember",
    "Emery",
    "Emma",
    "Ethan",
    "Eva",
    "Ezra",
    "Farah",
    "Felix",
    "Fiona",
    "Freya",
    "Gabriel",
    "Gemma",
    "Gianna",
    "Grace",
    "Harper",
    "Hazel",
    "Hugo",
    "Iris",
    "Isaac",
    "Isla",
    "Ivy",
    "Jace",
    "Jade",
    "Jalen",
    "Jamie",
    "Jasper",
    "Javier",
    "Jay",
    "Jordan",
    "Josephine",
    "Josie",
    "Jude",
    "Julia",
    "Jun",
    "Kai",
    "Kara",
    "Kieran",
    "Laila",
    "Lana",
    "Leo",
    "Leona",
    "Liam",
    "Lila",
    "Logan",
    "Lucia",
    "Luna",
    "Lydia",
    "Maia",
    "Marcus",
    "Maya",
    "Mia",
    "Micah",
    "Mila",
    "Milo",
    "Mina",
    "Nadia",
    "Naomi",
    "Nia",
    "Nico",
    "Nina",
    "Noah",
    "Nolan",
    "Nora",
    "Nova",
    "Omar",
    "Opal",
    "Orion",
    "Owen",
    "Paige",
    "Parker",
    "Penelope",
    "Phoebe",
    "Piper",
    "Priya",
    "Quinn",
    "Rafael",
    "Raya",
    "Remi",
    "Riley",
    "River",
    "Roman",
    "Ronan",
    "Rosa",
    "Rowan",
    "Ruby",
    "Ryan",
    "Sage",
    "Sam",
    "Sanaa",
    "Sari",
    "Scarlett",
    "Selene",
    "Shiloh",
    "Sienna",
    "Sofia",
    "Stella",
    "Summer",
    "Talia",
    "Theo",
    "Tessa",
    "Tristan",
    "Uma",
    "Val",
    "Vera",
    "Violet",
    "Willa",
    "Wyatt",
    "Xander",
    "Yasmin",
    "Zara",
    "Zane",
    "Zoe",
    "Aaron",
    "Abigail",
    "Adrian",
    "Alina",
    "Amir",
    "April",
    "Aurora",
    "Autumn",
    "Beckett",
    "Bella",
    "Bennett",
    "Caleb",
    "Celeste",
    "Colin",
    "Daisy",
    "Delilah",
    "Dominic",
    "Elena",
    "Elodie",
    "Finn",
    "Florence",
    "Gavin",
    "Georgia",
    "Griffin",
    "Hallie",
    "Heidi",
    "Holden",
    "Imogen",
    "Jonah",
    "Keira",
    "Knox",
    "Layla",
    "Maddox",
    "Margot",
    "Marnie",
    "Nathan",
    "Olive",
    "Poppy",
    "Reed",
    "Rosalie",
    "Sawyer",
    "Serena",
    "Simon",
    "Skye",
    "Soren",
    "Sydney",
    "Teagan",
    "Tobias",
    "Ulysses",
    "Vivienne",
    "Wesley",
    "Winter",
    "Yvette",
    "Yusuf",
    "Zarah",
    "Zoya",
    "Callum",
)


def _shortname(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.strip().lower()).strip("-")


def pick_unique_agent_name(existing: Sequence[tuple[str, str]]) -> str:
    used = {
        _shortname(name)
        for name, status in existing
        if status != "terminated" and name.strip()
    }
    available = [
        candidate for candidate in AGENT_NAME_POOL if _shortname(candidate) not in used
    ]
    pool = available or list(AGENT_NAME_POOL)
    return pool[secrets.randbelow(len(pool))] if pool else "Agent"
